function [f] = flexibleCPD(u, W, V, c_toy, r)
    P = zeros(r,1);
    x = V' * u;
    for i=1:r
        P(i,1) = c_toy((6* (i - 1)) + 1) + ...
                 c_toy((6* (i - 1)) + 2) * x(i) + ...
                 c_toy((6* (i - 1)) + 3) * x(i)^2 + ...
                 c_toy((6* (i - 1)) + 4) * x(i)^3 + ...
                 c_toy((6* (i - 1)) + 5) * x(i)^4 + ...
                 c_toy((6* (i - 1)) + 6) * x(i)^5; % + ...
%                  c_toy((11* (i - 1)) + 7) * x(i)^6 + ...
%                  c_toy((11* (i - 1)) + 8) * x(i)^7 + ...
%                  c_toy((11* (i - 1)) + 9) * x(i)^8 + ...
%                  c_toy((11* (i - 1)) + 10) * x(i)^9 + ...
%                  c_toy((11* (i - 1)) + 11) * x(i)^10;
    end
    f = W * P;
end

